// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFsk89IndfYVWX5x960QbbOtC7Y9-55aE',
    appId: '1:878128902123:web:35ee10f5bedac5c68133ae',
    messagingSenderId: '878128902123',
    projectId: 'gacha-guard-3b807',
    authDomain: 'gacha-guard-3b807.firebaseapp.com',
    storageBucket: 'gacha-guard-3b807.firebasestorage.app',
    measurementId: 'G-9JY76F19QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSvhECkse4sdE50JcAm-lqVdbLYLZ4jc8',
    appId: '1:878128902123:android:aa9ddf64d81070798133ae',
    messagingSenderId: '878128902123',
    projectId: 'gacha-guard-3b807',
    storageBucket: 'gacha-guard-3b807.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByiHnI9LrDzt2pp7d0BUmIoK9oR4SReSA',
    appId: '1:878128902123:ios:1ac7a9e512f1abbc8133ae',
    messagingSenderId: '878128902123',
    projectId: 'gacha-guard-3b807',
    storageBucket: 'gacha-guard-3b807.firebasestorage.app',
    androidClientId: '878128902123-j5trdbdsmbfp18glrqfggojf11sv9knu.apps.googleusercontent.com',
    iosClientId: '878128902123-1n9c6eauu89smvougciq9b79i886a1ln.apps.googleusercontent.com',
    iosBundleId: 'com.ekofoo.gachaguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFsk89IndfYVWX5x960QbbOtC7Y9-55aE',
    appId: '1:878128902123:web:9518e05ade2cd8518133ae',
    messagingSenderId: '878128902123',
    projectId: 'gacha-guard-3b807',
    authDomain: 'gacha-guard-3b807.firebaseapp.com',
    storageBucket: 'gacha-guard-3b807.firebasestorage.app',
    measurementId: 'G-5C1429DE0V',
  );

}